=== Jhaldreen/DAM-Primero/LMGSI/jimenez_sevilla_antonio_LMGSI06_Tarea/Ejercicio2/Ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Definicion del vocabulario -->
    <xs:element name="Centros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "Ciclos" type= "tipoCiclos"></xs:element>
                <xs:element name = "Alumnos" type= "tipoAlumnos"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
        
        <!-- Tabla ciclos-->
        <xs:complexType name="tipoCiclos">
            <xs:sequence>
                <xs:element name = "Ciclo" type="tipoCiclo" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    
        <!-- Definicion de cada fila de la tabla ciclos-->
        <xs:complexType name="tipoCiclo">
            <xs:sequence>
                <xs:element name="nombre" type="tipoNombreC"/>
                <xs:element name="grado" type="tipoGrado"/>
            </xs:sequence>
            <xs:attribute name="ciclo_no" type="tipoCiclo_no" use="required"/>
        </xs:complexType>
    
        <!-- Restricción para el elemento "nombre" del ciclo -->
         <xs:simpleType name="tipoNombreC">
             <xs:restriction base = "xs:string">
                 <xs:maxLength value="50"/>
             </xs:restriction>
         </xs:simpleType>
        
        <!-- Restricción para el elemento "grado" -->
        <xs:simpleType name="tipoGrado">
            <xs:restriction base = "xs:string">
                <xs:maxLength value="3"/>
            </xs:restriction>
        </xs:simpleType>
    
        <!-- Restricción para el atributo "tipoCiclo_no" -->
        <xs:simpleType name="tipoCiclo_no">
            <xs:restriction base = "xs:ID">
                <xs:maxLength value="4"/>
            </xs:restriction>
        </xs:simpleType>
    
        <!-- Tabla alumnos-->
        <xs:complexType name="tipoAlumnos">
            <xs:sequence>
                <xs:element name="Alumno" type="tipoAlumno" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    
        <!-- Definicion de cada fila de la tabla alumnos-->
        <xs:complexType name="tipoAlumno">
            <xs:sequence>
                <xs:element name= "apellidos" type = "tipoApellidos"/>
                <xs:element name= "nombre" type = "tipoDato"/>
                <xs:element name= "dni" type = "tipoDNI" minOccurs="1"/>
                <xs:element name= "fecha_matricula" type = "xs:date"/>
                <xs:element name= "direccion" type = "tipoDato"/>
                <xs:element name= "localidad" type = "tipoDato"/>
                <xs:element name= "provincia" type = "tipoDato"/>
                <xs:element name= "tfno" type = "tipoTelefono"/>
            </xs:sequence>
            <xs:attribute name="alumno_no" type="tipoAlumno_no" use="required"/>
            <xs:attribute name="ciclo_no" type="xs:IDREF" use="required"/>
        </xs:complexType>
    
         <!-- Restricción para el elemento "apellidos" -->
         <xs:simpleType name="tipoApellidos">
             <xs:restriction base = "xs:string">
                 <xs:maxLength value="30"/>
             </xs:restriction>
         </xs:simpleType>
    
        <!-- Restricción para los elementos "nombre" / "direccion" / "localidad" / "provincia" -->
        <xs:simpleType name="tipoDato">
            <xs:restriction base = "xs:string">
                <xs:maxLength value="30"/>
            </xs:restriction>
        </xs:simpleType>
    
        <!-- Restricción para el elemento "dni" -->
        <xs:simpleType name="tipoDNI">
            <xs:restriction base = "xs:string">
                <xs:minLength value="1"/>
                <xs:maxLength value="9"/>
            </xs:restriction>
        </xs:simpleType>
    
         <!-- Restricción para el elemento "telefono" -->
        <xs:simpleType name="tipoTelefono">
            <xs:restriction base = "xs:string">
                <xs:maxLength value="9"/>
            </xs:restriction>
        </xs:simpleType>
    
        <!-- Restricción para el atributo "tipoCiclo_no" -->
        <xs:simpleType name="tipoAlumno_no">
            <xs:restriction base = "xs:ID">
                <xs:maxLength value="5"/>
            </xs:restriction>
        </xs:simpleType>
        
</xs:schema>

=== Jhaldreen/DAM-Primero/LMGSI/jimenez_sevilla_antonio_LMGSI06_Tarea/Ejercicio2/Centros.xml
<?xml version="1.0" encoding="UTF-8"?>
<Centros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio2.xsd">
    <Ciclos>
        <Ciclo ciclo_no = "C010">
            <nombre>Desarrollo de aplicaciones web</nombre>
            <grado>GS</grado>
        </Ciclo>
        <Ciclo ciclo_no = "C020">
            <nombre>Desarrollo de aplicaciones multiplataforma</nombre>
            <grado>GS</grado>
        </Ciclo>
        <Ciclo ciclo_no = "C030">
            <nombre>Sistemas microinformaticos y redes</nombre>
            <grado>GM</grado>
        </Ciclo>
        <Ciclo ciclo_no = "C040">
            <nombre>Administracion y finanzas</nombre>
            <grado>GS</grado>
        </Ciclo>
    </Ciclos>
    
    <Alumnos>
        <Alumno alumno_no = "A1248" ciclo_no = "C010">
            <apellidos>Fernandez Ruiz</apellidos>
            <nombre>Angel</nombre>
            <dni>78922561A</dni>
            <fecha_matricula>2020-07-13</fecha_matricula>
            <direccion>c/ El Pez, 12</direccion>
            <localidad>Laredo</localidad>
            <provincia>Cantabria</provincia>
            <tfno>666223344</tfno>
        </Alumno>
        <Alumno alumno_no = "A1344" ciclo_no = "C020">
            <apellidos>Lopez Garcia</apellidos>
            <nombre>Eva</nombre>
            <dni>13466544T</dni>
            <fecha_matricula>2020-07-12</fecha_matricula>
            <direccion>Avda. La presa, 45</direccion>
            <localidad>Colindres</localidad>
            <provincia>Cantabria</provincia>
            <tfno>677898917</tfno>
        </Alumno>
        <Alumno alumno_no = "A1401" ciclo_no = "C020">
            <apellidos>López Haro</apellidos>
            <nombre>Fernando</nombre>
            <dni>78665432D</dni>
            <fecha_matricula>2020-07-19</fecha_matricula>
            <direccion>Avda. Gral. Espinosa, 33</direccion>
            <localidad>Treto</localidad>
            <provincia>Cantabria</provincia>
            <tfno>654323232</tfno>
        </Alumno>
        <Alumno alumno_no = "A1899" ciclo_no = "C040">
            <apellidos>Muro Hoz</apellidos>
            <nombre>Luis Ángel</nombre>
            <dni>72314522S</dni>
            <fecha_matricula>2020-07-12</fecha_matricula>
            <direccion>c/ Miguel Hernandez, 15</direccion>
            <localidad>Granada</localidad>
            <provincia>Granada</provincia>
            <tfno>633242526</tfno>
        </Alumno>
        <Alumno alumno_no = "A2155" ciclo_no = "C030">
            <apellidos>Ruiz Ruiz</apellidos>
            <nombre>Diego</nombre>
            <dni>71345666B</dni>
            <fecha_matricula>2020-07-16</fecha_matricula>
            <direccion>c/ Argentina, 12</direccion>
            <localidad>Santander</localidad>
            <provincia>Cantabria</provincia>
            <tfno>666777888</tfno>
        </Alumno>
        <Alumno alumno_no = "A2222" ciclo_no = "C030">
            <apellidos>Coronas Gomez</apellidos>
            <nombre>Rosa</nombre>
            <dni>72133445R</dni>
            <fecha_matricula>2020-07-11</fecha_matricula>
            <direccion>c/ Castilla, 37</direccion>
            <localidad>Bezana</localidad>
            <provincia>Cantabria</provincia>
            <tfno>659876544</tfno>
        </Alumno>
    </Alumnos>
</Centros>
